# Generated by Django 6.0.1 on 2026-01-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_number')},
        ),
    ]
