# Generated by Django 6.0.1 on 2026-02-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowstep_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='type',
            field=models.CharField(default='HTTP', max_length=50),
        ),
        migrations.AlterField(
            model_name='execution',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
