# Generated by Django 6.0.1 on 2026-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_executionsteplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionsteplog',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Successful'), ('F', 'Failed'), ('K', 'Skipped')], max_length=1),
        ),
    ]
